// Generated by CoffeeScript 1.8.0
var VALUE_MAP;

VALUE_MAP = {
  "00": 'firmwareVersion',
  "01": 'temperature',
  "02": 'vibration',
  "03": 'orientation',
  "04": 'isVibrating',
  "05": 'batteryVoltage',
  "07": 'updateMode'
};

module.exports = function(response) {
  return response;
};
