// Generated by CoffeeScript 1.8.0
var presentTime, presentValues;

presentTime = require('./time');

presentValues = require('./values');

module.exports = function(response) {
  return {
    time: presentTime(response),
    values: presentValues(response)
  };
};
