// Generated by CoffeeScript 1.8.0
var presentMetadata, presentTime, presentValues;

presentMetadata = require('./meta');

presentTime = require('./time');

presentValues = require('./values');

module.exports = function(response) {
  var values;
  values = presentValues(response);
  return {
    meta: presentMetadata(response, values),
    time: presentTime(response),
    values: values
  };
};
