// Generated by CoffeeScript 1.9.3
var presentBatteryStrength, presentMetadata, presentWiFiStrength;

presentMetadata = function(response, arg) {
  var batteryVoltage;
  batteryVoltage = arg.batteryVoltage;
  return {
    battery: presentBatteryStrength(batteryVoltage),
    wifiSignal: presentWiFiStrength(response)
  };
};

presentBatteryStrength = function(voltage) {
  if (voltage) {
    if (voltage < 1.3) {
      return 'plugged in';
    }
    switch (false) {
      case !(voltage > 2.75):
        return 'full';
      case !(voltage > 2.6):
        return '2/3';
      case !(voltage > 2.45):
        return '1/3';
      default:
        return 'weak';
    }
  } else {
    return 'unknown';
  }
};

presentWiFiStrength = function(response) {
  var strength;
  if (strength = response.rssi) {
    switch (false) {
      case !(strength > 203):
        return 'full';
      case !(strength > 195):
        return '2/3';
      case !(strength > 185):
        return '1/3';
      default:
        return 'weak';
    }
  } else {
    return 'unknown';
  }
};

module.exports = presentMetadata;
