// Generated by CoffeeScript 1.8.0
module.exports = function(response) {
  var compage, dataAt, now;
  console.log('from response:');
  console.log('--------------');
  console.log(' > lp (date):', new Date(response.last_poll * 1000));
  console.log(' > ts (date):', new Date(response.ts * 1000));
  console.log(' >        ts:', response.ts);
  console.log(' > now(date):', now = new Date());
  console.log(' >       now:', now.getTime());
  console.log(' >       age:', response.age);
  console.log(' > ts -> now:', (now / 1000) - response.ts);
  console.log(' > ts -> min:', ((now / 1000) - response.ts) / 60);
  console.log('---');
  console.log('-data', dataAt = new Date(response.ts * 1000));
  console.log('-age', response.age);
  console.log('-computed age', compage = (now / 1000) - response.ts);
  console.log(' > age in minutes:', ((now / 1000) - response.ts) / 60);
  return console.log('age diff (comp vs. actual)', compage - response.age);
};
