// Generated by CoffeeScript 1.9.3
var VALUE_MAP, makeValuesUseful, presentValues;

VALUE_MAP = {
  "00": 'firmwareVersion',
  "01": 'temperature',
  "02": 'vibration',
  "03": 'orientation',
  "04": 'isVibrating',
  "05": 'batteryVoltage',
  "07": 'updateMode'
};

presentValues = function(response) {
  var friendlyName, i, identifier, key, len, output, ref, tuple, value;
  output = {};
  ref = response.values;
  for (i = 0, len = ref.length; i < len; i++) {
    tuple = ref[i];
    key = tuple[0], value = tuple[1];
    identifier = key.substr(-2, 2);
    if (friendlyName = VALUE_MAP[identifier]) {
      output[friendlyName] = value;
    }
  }
  return makeValuesUseful(output);
};

makeValuesUseful = function(values) {
  values.temperature = values.temperature / 100;
  values.isVibrating = values.isVibrating === 0 ? false : true;
  values.batteryVoltage = Math.round(values.batteryVoltage / 10000) / 100;
  values.updateMode = values.updateMode === 0 ? 'normal' : 'fast';
  return values;
};

module.exports = presentValues;
