// Generated by CoffeeScript 1.8.0
var VALUE_MAP, makeValuesUseful, presentValues;

VALUE_MAP = {
  "00": 'firmwareVersion',
  "01": 'temperature',
  "02": 'vibration',
  "03": 'orientation',
  "04": 'isVibrating',
  "05": 'batteryVoltage',
  "07": 'updateMode'
};

presentValues = function(response) {
  var friendlyName, identifier, key, output, tuple, value, _i, _len, _ref;
  output = {};
  _ref = response.values;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    tuple = _ref[_i];
    key = tuple[0], value = tuple[1];
    identifier = key.substr(-2, 2);
    if (friendlyName = VALUE_MAP[identifier]) {
      output[friendlyName] = value;
    }
  }
  return makeValuesUseful(output);
};

makeValuesUseful = function(values) {
  values.temperature = values.temperature / 100;
  values.isVibrating = values.isVibrating === 0 ? false : true;
  values.updateMode = values.updateMode === 0 ? 'normal' : 'fast';
  return values;
};

module.exports = presentValues;
